server:
  port: 19123

token:
  secretKey: bd0da7ed28e14b3296ed8da9f14e2266

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/tolog
    username: username
    password: password
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 5
      max-lifetime: 1800000
  thymeleaf:
    cache: false

mybatis-plus:
  typeAliasesPackage: com.hidou7.tolog.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

tolog:
  username: admin
  password: admin