server:
  port: 19123

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tolog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: username
    password: password
  thymeleaf:
    cache: false

mybatis-plus:
  typeAliasesPackage: io.github.hidou7.tolog.entity

tolog:
  username: admin
  password: admin